### PR TITLE
Updated Realm to v2.0.2

### PR DESCRIPTION
**Pull request by Sirrah**
I've also updated the Gradle wrapper, build tools and support libs.

I haven't looked into the differences between `getTableOrView()` and the original `getTable()` but it seems to work.

The example app depends on the realm-nytimes-data project also using Realm 2.0.2. For which I've prepared another pr: thorbenprimke/realm-nytimes-data#1

### CODE REVIEW

**Review by johnjoseph — COMMENTED** [review]
The realmResults.getTable() to realmResults.getTableOrView() is vital as it's breaking in 2.0.2 for me and forcing me to downgrade to 1.1.0

**Comment by noomz** [comment]
+1 (now latest Realm is 2.1.0)

**Comment by thorbenprimke** [comment]
Sorry that I just haven't been good about reviewing and approving these. This looks good. I'll merge it and verify it all works. Once that's done I'll update to latest version and make another release.

**Comment by thorbenprimke** [comment]
New build is out. 

```
	        compile 'com.github.thorbenprimke:realm-recyclerview:0.9.24'
```

I went ahead and upgraded it to Realm 2.2.1. I verified with the Example app that the demos / examples still work. 

@Sirrah - thanks for putting the PR up.

**Comment by Sirrah** [comment]
@thorbenprimke You're welcome. Thank you for creating a new build with the latest Realm included.

**Pull request merged**
